export const states = {
    AL: {name: "Alabama", color: "red", points: 9},
//    AK: {name: "Alaska", color: "red", points: 3},
    AZ: {name: "Arizona", color: "red", points: 11},
    AR: {name: "Arkansas", color: "blue", points: 6},
    CA: {name: "California", color: "blue", points: 54},
    CO: {name: "Colorado", color: "blue", points: 10},
    CT: {name: "Connecticut", color: "green", points: 7},
    DE: {name: "Delaware", color: "yellow", points: 3},
//    DC: {name: "District of Columbia", color: "red", points: 3},
    FL: {name: "Florida", color: "yellow", points: 30},
    GA: {name: "Georgia", color: "blue", points: 16},
//    HI: {name: "Hawaii", color: "red", points: 4},
    ID: {name: "Idaho", color: "red", points: 4},
    IL: {name: "Illinois", color: "blue", points: 19},
    IN: {name: "Indiana", color: "yellow", points: 11},
    IA: {name: "Iowa", color: "yellow", points: 6},
    KS: {name: "Kansas", color: "yellow", points: 6},
    KY: {name: "Kentucky", color: "green", points: 8},
    LA: {name: "Louisiana", color: "yellow", points: 8},
    ME: {name: "Maine", color: "blue", points: 4},
    MD: {name: "Maryland", color: "blue", points: 10},
    MA: {name: "Massachusetts", color: "red", points: 11},
    MI: {name: "Michigan", color: "blue", points: 15},
    MN: {name: "Minnesota", color: "green", points: 10},
    MS: {name: "Mississippi", color: "green", points: 6},
    MO: {name: "Missouri", color: "red", points: 10},
    MT: {name: "Montana", color: "green", points: 4},
    NE: {name: "Nebraska", color: "green", points: 5},
    NV: {name: "Nevada", color: "yellow", points: 6},
    NH: {name: "New Hampshire", color: "green", points: 4},
    NJ: {name: "New Jersey", color: "red", points: 14},
    NM: {name: "New Mexico", color: "yellow", points: 5},
    NY: {name: "New York", color: "blue", points: 28},
    NC: {name: "North Carolina", color: "green", points: 16},
    ND: {name: "North Dakota", color: "blue", points: 3},
    OH: {name: "Ohio", color: "red", points: 17},
    OK: {name: "Oklahoma", color: "green", points: 7},
    OR: {name: "Oregon", color: "green", points: 8},
    PA: {name: "Pennsylvania", color: "green", points: 19},
    RI: {name: "Rhode Island", color: "blue", points: 4},
    SC: {name: "South Carolina", color: "red", points: 9},
    SD: {name: "South Dakota", color: "red", points: 3},
    TN: {name: "Tennessee", color: "yellow", points: 11},
    TX: {name: "Texas", color: "red", points: 40},
    UT: {name: "Utah", color: "green", points: 6},
    VT: {name: "Vermont", color: "yellow", points: 3},
    VA: {name: "Virginia", color: "red", points: 13},
    WA: {name: "Washington", color: "blue", points: 12},
    WV: {name: "West Virginia", color: "yellow", points: 4},
    WI: {name: "Wisconsin", color: "red", points: 10},
    WY: {name: "Wyoming", color: "yellow", points: 3},
};

export const map = [
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","WA","WA","WA","ID","MT","MT","MT","MT","MT","MT","MT","MT","ND","ND","ND","ND","ND","MN","MN","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["WA","WA","WA","WA","ID","MT","MT","MT","MT","MT","MT","MT","MT","ND","ND","ND","ND","ND","MN","MN","MN","MN","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","ME","ME",],
    ["WA","WA","WA","WA","ID","MT","MT","MT","MT","MT","MT","MT","MT","ND","ND","ND","ND","ND","MN","MN","MN","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","ME","ME",],
    ["OR","OR","OR","OR","ID","ID","MT","MT","MT","MT","MT","MT","MT","SD","SD","SD","SD","SD","MN","MN","MN","WI","WI","MI","MI","MI","  ","  ","  ","  ","  ","  ","  ","NY","VT","NH","ME","ME","  ",],
    ["OR","OR","OR","OR","ID","ID","ID","MT","WY","WY","WY","WY","WY","SD","SD","SD","SD","SD","MN","MN","MN","WI","WI","WI","  ","  ","MI","  ","  ","  ","  ","  ","NY","NY","VT","NH","ME","  ","  ",],
    ["OR","OR","OR","OR","ID","ID","ID","ID","WY","WY","WY","WY","WY","SD","SD","SD","SD","SD","MN","MN","MN","MN","WI","WI","  ","MI","MI","  ","  ","  ","  ","NY","NY","NY","MA","MA","MA","  ","  ",],
    ["OR","OR","OR","OR","ID","ID","ID","ID","WY","WY","WY","WY","WY","NE","NE","NE","NE","NE","IA","IA","IA","IA","WI","WI","  ","MI","MI","  ","  ","PA","NY","NY","NY","NY","CT","RI","MA","  ","  ",],
    ["CA","CA","NV","NV","NV","NV","UT","UT","WY","WY","WY","WY","WY","NE","NE","NE","NE","NE","IA","IA","IA","IA","IL","IL","IN","IN","OH","OH","OH","PA","PA","PA","PA","NJ","NY","  ","  ","  ","  ",],
    ["CA","CA","NV","NV","NV","NV","UT","UT","UT","UT","CO","CO","CO","CO","CO","NE","NE","NE","IA","IA","IA","IL","IL","IL","IN","IN","OH","OH","OH","PA","PA","PA","PA","NJ","  ","  ","  ","  ","  ",],
    ["CA","CA","NV","NV","NV","NV","UT","UT","UT","UT","CO","CO","CO","CO","CO","KS","KS","KS","KS","MO","MO","IL","IL","IL","IN","IN","OH","OH","WV","WV","WV","VA","MD","DE","  ","  ","  ","  ","  ",],
    ["  ","CA","CA","NV","NV","NV","UT","UT","UT","UT","CO","CO","CO","CO","CO","KS","KS","KS","KS","MO","MO","MO","IL","IL","IN","KY","KY","KY","WV","WV","VA","VA","VA","MD","  ","  ","  ","  ","  ",],
    ["  ","CA","CA","CA","NV","NV","UT","UT","UT","UT","CO","CO","CO","CO","CO","KS","KS","KS","KS","MO","MO","MO","MO","KY","KY","KY","KY","KY","VA","VA","VA","VA","VA","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","CA","CA","CA","NV","AZ","AZ","AZ","AZ","NM","NM","NM","NM","OK","OK","OK","OK","OK","MO","MO","MO","MO","TN","TN","TN","TN","TN","NC","NC","NC","NC","NC","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","CA","CA","CA","AZ","AZ","AZ","AZ","NM","NM","NM","NM","TX","TX","OK","OK","OK","AR","AR","AR","TN","TN","TN","TN","TN","NC","NC","NC","NC","NC","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","CA","CA","AZ","AZ","AZ","AZ","NM","NM","NM","NM","TX","TX","OK","OK","OK","AR","AR","MS","MS","AL","AL","AL","GA","GA","SC","SC","NC","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","CA","AZ","AZ","AZ","AZ","NM","NM","NM","NM","TX","TX","TX","TX","TX","AR","AR","MS","MS","AL","AL","AL","GA","GA","SC","SC","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","AZ","AZ","AZ","NM","TX","TX","TX","TX","TX","TX","TX","TX","LA","LA","MS","MS","AL","AL","AL","GA","GA","GA","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","TX","TX","TX","TX","TX","TX","TX","LA","LA","MS","MS","AL","AL","AL","GA","GA","GA","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","TX","TX","TX","TX","TX","LA","LA","LA","MS","AL","FL","FL","FL","FL","FL","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","TX","TX","TX","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","FL","FL","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","TX","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","FL","FL","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","FL","FL","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","FL","FL","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
]

export const tints = map.map(row => row.map(state => states[state] ? states[state].color : null));
