export const states = {
    AL: {name: "Alabama", color: "red"},
//    AK: {name: "Alaska", color: "red"},
    AZ: {name: "Arizona", color: "red"},
    AR: {name: "Arkansas", color: "blue"},
    CA: {name: "California", color: "blue"},
    CO: {name: "Colorado", color: "blue"},
    CT: {name: "Connecticut", color: "green"},
    DE: {name: "Delaware", color: "yellow"},
//    DC: {name: "District of Columbia", color: "red"},
    FL: {name: "Florida", color: "yellow"},
    GA: {name: "Georgia", color: "blue"},
//    HI: {name: "Hawaii", color: "red"},
    ID: {name: "Idaho", color: "red"},
    IL: {name: "Illinois", color: "blue"},
    IN: {name: "Indiana", color: "yellow"},
    IA: {name: "Iowa", color: "yellow"},
    KS: {name: "Kansas", color: "yellow"},
    KY: {name: "Kentucky", color: "green"},
    LA: {name: "Louisiana", color: "yellow"},
    ME: {name: "Maine", color: "blue"},
    MD: {name: "Maryland", color: "blue"},
    MA: {name: "Massachusetts", color: "red"},
    MI: {name: "Michigan", color: "blue"},
    MN: {name: "Minnesota", color: "green"},
    MS: {name: "Mississippi", color: "green"},
    MO: {name: "Missouri", color: "red"},
    MT: {name: "Montana", color: "green"},
    NE: {name: "Nebraska", color: "green"},
    NV: {name: "Nevada", color: "yellow"},
    NH: {name: "New Hampshire", color: "green"},
    NJ: {name: "New Jersey", color: "red"},
    NM: {name: "New Mexico", color: "yellow"},
    NY: {name: "New York", color: "blue"},
    NC: {name: "North Carolina", color: "green"},
    ND: {name: "North Dakota", color: "blue"},
    OH: {name: "Ohio", color: "red"},
    OK: {name: "Oklahoma", color: "green"},
    OR: {name: "Oregon", color: "green"},
    PA: {name: "Pennsylvania", color: "green"},
    RI: {name: "Rhode Island", color: "blue"},
    SC: {name: "South Carolina", color: "red"},
    SD: {name: "South Dakota", color: "red"},
    TN: {name: "Tennessee", color: "yellow"},
    TX: {name: "Texas", color: "red"},
    UT: {name: "Utah", color: "green"},
    VT: {name: "Vermont", color: "yellow"},
    VA: {name: "Virginia", color: "red"},
    WA: {name: "Washington", color: "blue"},
    WV: {name: "West Virginia", color: "yellow"},
    WI: {name: "Wisconsin", color: "red"},
    WY: {name: "Wyoming", color: "yellow"},
};

export const map = [
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","WA","WA","WA","ID","MT","MT","MT","MT","MT","MT","MT","MT","ND","ND","ND","ND","ND","MN","MN","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["WA","WA","WA","WA","ID","MT","MT","MT","MT","MT","MT","MT","MT","ND","ND","ND","ND","ND","MN","MN","MN","MN","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","ME","ME",],
    ["WA","WA","WA","WA","ID","MT","MT","MT","MT","MT","MT","MT","MT","ND","ND","ND","ND","ND","MN","MN","MN","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","ME","ME",],
    ["OR","OR","OR","OR","ID","ID","MT","MT","MT","MT","MT","MT","MT","SD","SD","SD","SD","SD","MN","MN","MN","WI","WI","MI","MI","MI","  ","  ","  ","  ","  ","  ","  ","NY","VT","NH","ME","ME","  ",],
    ["OR","OR","OR","OR","ID","ID","ID","MT","WY","WY","WY","WY","WY","SD","SD","SD","SD","SD","MN","MN","MN","WI","WI","WI","  ","  ","MI","  ","  ","  ","  ","  ","NY","NY","VT","NH","ME","  ","  ",],
    ["OR","OR","OR","OR","ID","ID","ID","ID","WY","WY","WY","WY","WY","SD","SD","SD","SD","SD","MN","MN","MN","MN","WI","WI","  ","MI","MI","  ","  ","  ","  ","NY","NY","NY","MA","MA","MA","  ","  ",],
    ["OR","OR","OR","OR","ID","ID","ID","ID","WY","WY","WY","WY","WY","NE","NE","NE","NE","NE","IA","IA","IA","IA","WI","WI","  ","MI","MI","  ","  ","PA","NY","NY","NY","NY","CT","RI","MA","  ","  ",],
    ["CA","CA","NV","NV","NV","NV","UT","UT","WY","WY","WY","WY","WY","NE","NE","NE","NE","NE","IA","IA","IA","IA","IL","IL","IN","IN","OH","OH","OH","PA","PA","PA","PA","NJ","NY","  ","  ","  ","  ",],
    ["CA","CA","NV","NV","NV","NV","UT","UT","UT","UT","CO","CO","CO","CO","CO","NE","NE","NE","IA","IA","IA","IL","IL","IL","IN","IN","OH","OH","OH","PA","PA","PA","PA","NJ","  ","  ","  ","  ","  ",],
    ["CA","CA","NV","NV","NV","NV","UT","UT","UT","UT","CO","CO","CO","CO","CO","KS","KS","KS","KS","MO","MO","IL","IL","IL","IN","IN","OH","OH","WV","WV","WV","VA","MD","DE","  ","  ","  ","  ","  ",],
    ["  ","CA","CA","NV","NV","NV","UT","UT","UT","UT","CO","CO","CO","CO","CO","KS","KS","KS","KS","MO","MO","MO","IL","IL","IN","KY","KY","KY","WV","WV","VA","VA","VA","MD","  ","  ","  ","  ","  ",],
    ["  ","CA","CA","CA","NV","NV","UT","UT","UT","UT","CO","CO","CO","CO","CO","KS","KS","KS","KS","MO","MO","MO","MO","KY","KY","KY","KY","KY","VA","VA","VA","VA","VA","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","CA","CA","CA","NV","AZ","AZ","AZ","AZ","NM","NM","NM","NM","OK","OK","OK","OK","OK","MO","MO","MO","MO","TN","TN","TN","TN","TN","NC","NC","NC","NC","NC","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","CA","CA","CA","AZ","AZ","AZ","AZ","NM","NM","NM","NM","TX","TX","OK","OK","OK","AR","AR","AR","TN","TN","TN","TN","TN","NC","NC","NC","NC","NC","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","CA","CA","AZ","AZ","AZ","AZ","NM","NM","NM","NM","TX","TX","OK","OK","OK","AR","AR","MS","MS","AL","AL","AL","GA","GA","SC","SC","NC","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","CA","AZ","AZ","AZ","AZ","NM","NM","NM","NM","TX","TX","TX","TX","TX","AR","AR","MS","MS","AL","AL","AL","GA","GA","SC","SC","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","AZ","AZ","AZ","NM","TX","TX","TX","TX","TX","TX","TX","TX","LA","LA","MS","MS","AL","AL","AL","GA","GA","GA","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","TX","TX","TX","TX","TX","TX","TX","LA","LA","MS","MS","AL","AL","AL","GA","GA","GA","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","TX","TX","TX","TX","TX","LA","LA","LA","MS","AL","FL","FL","FL","FL","FL","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","TX","TX","TX","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","FL","FL","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","TX","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","FL","FL","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","FL","FL","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","FL","FL","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
    ["  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ","  ",],
]

export const tints = map.map(row => row.map(state => states[state] ? states[state].color : null));
